package Sort;

import java.sql.ResultSet;

/**
 * Yuecheng Rong
 */

/**
 * This is the interface of "SortBy" function,
 * which is the skeleton of all the sorting functions.
 * That includes sort by rate / waiting time / average price / distance
 */
public interface Skeleton
{

    /** Helper function to set the Query. */
    void setQuery(String Query);

    /** Helper function to clear the super array */
    void clearSuper();

    /**
     * Input a query and do the sorting.
     * Sorting is done by executing different queries
     *
     * @param city the city of the customer lives
     * @param province the province of the customer lives
     */
    void doSort(String city, String province, int customer_id);

    /**
     * This is a helper function to change the statement of Query
     * Will be use by sort in both login and not login situation
     *
     * @param city the city of the customer lives
     * @param province the province of the customer lives
     */
    void inputSituation(String city, String province);

    /**
     * This is a helper function to store the information generated into the super array
     * Will be use by sort in both login and not login situation
     *
     * @param resultSet the result generated by executing SQL
     */
    void setSortInfos(ResultSet resultSet);

    /**
     * This is a helper function to generate the distance if customer is logged in
     *
     * @param customer_id the logged in customer's id
     */
    void afterLogin(int customer_id);

    /**
     * Helper function that can print the super array on the console.
     */
    void printSuperArray();

}
